### ISSUE TITLE
Error Writing to DB, Player Data Reset

### ISSUE THREAD

**Issue by Zindswini** [Athlaeos/ValhallaMMO#9]
Version: Beta 1.0.7
Server: Paper 1.20.4 Build 463

Hi, my friends and I have been using this plugin for a couple weeks now, and its been an absolute blast. Thank you!

That said, we've run into an error twice where the server will freeze and crash. When it comes back up, some of the skills are reset to zero. So far this has only happened to one of the players, but he was also the only one online both times.

I keep backups, and I was able to restore his progress by restoring individual table rows from backup.

I've included the log, it seems to error when writing to the database. In the mean time, I'll update to the latest beta and see if it happens again.

Thank you!

```
[11:03:39] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-463 (MC: 1.20.4) ---
[11:03:39] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 48706ms or 974 ticks behind
[11:03:39] [Paper Watchdog Thread/ERROR]: The server has not responded for -37 seconds! Creating thread dump
[11:03:39] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:03:39] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[11:03:40] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.level.EntityPlayer
[11:03:40] [VoiceChatPacketProcessingThread/ERROR]: Dropping voice chat packets! Your Server might be overloaded!
[11:03:40] [VoiceChatPacketProcessingThread/ERROR]: Packet queue has 0 packets
[11:03:40] [VoiceChatPacketProcessingThread/INFO]: Player ___ timed out
[11:03:40] [VoiceChatPacketProcessingThread/INFO]: Reconnecting player ___
[11:03:40] [VoiceChatPacketProcessingThread/INFO]: Sent secret to ___
[11:03:40] [Paper Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[11:03:40] [Paper Watchdog Thread/ERROR]: Entity UUID: ___
[11:03:40] [Paper Watchdog Thread/ERROR]: Position: world: 'world' at location (-2062.955576876395, 78.0, 926.2776468237606)
[11:03:40] [Paper Watchdog Thread/ERROR]: Velocity: (0.0, -0.0784000015258789, 0.0) (in blocks per tick)
[11:03:40] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[-2062.025382133649, 78.0, 925.2756916162667] -> [-2061.4253821098073, 79.79999995231628, 925.8756916401086]
[11:03:40] [Paper Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 344768
[11:03:40] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:03:40] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[11:03:40] [Paper Watchdog Thread/ERROR]: 	PID: 25 | Suspended: false | Native: true | State: RUNNABLE
[11:03:40] [Paper Watchdog Thread/ERROR]: 	Stack:
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.io.RandomAccessFile.readBytes(Native Method)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.io.RandomAccessFile.read(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.io.RandomAccessFile.readFully(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.zip.ZipFile$Source.readFullyAt(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.zip.InflaterInputStream.read(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.Manifest$FastInputStream.fill(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.Manifest$FastInputStream.readLine(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.Manifest$FastInputStream.readLine(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.Attributes.read(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.Manifest.read(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.Manifest.<init>(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.Manifest.<init>(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.JarFile.getManifestFromReference(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.util.jar.JarFile.getManifest(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.net.URLClassLoader.defineClass(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.net.URLClassLoader$1.run(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.net.URLClassLoader$1.run(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.security.AccessController.executePrivileged(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.security.AccessController.doPrivileged(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.net.URLClassLoader.findClass(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.lang.ClassLoader.loadClass(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.lang.ClassLoader.loadClass(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:113)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:97)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:347)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.layout.PatternLayout$NoFormatPatternSerializer.toSerializable(PatternLayout.java:342)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:215)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.core.Logger.log(Logger.java:162)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2671)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.util.ForwardLogHandler.publish(ForwardLogHandler.java:34)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.logging@17.0.10/java.util.logging.Logger.log(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.logging@17.0.10/java.util.logging.Logger.doLog(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.logging@17.0.10/java.util.logging.Logger.log(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:492)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6363/0x00007f13f3b90248.run(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.10/java.lang.Thread.run(Unknown Source)
[11:03:40] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:03:40] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[11:03:40] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:03:40] [Server thread/WARN]: Task #2500160 for ValhallaMMO vBETA-1.0.7 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:?]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:?]
	at java.util.HashMap.putMapEntries(Unknown Source) ~[?:?]
	at java.util.HashMap.<init>(Unknown Source) ~[?:?]
	at me.athlaeos.valhallammo.playerstats.AccumulativeStatManager.lambda$attemptMapCleanup$0(AccumulativeStatManager.java:473) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-463]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-463]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-463]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-463]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-463]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-463]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-463]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[11:03:41] [Server thread/INFO]: ___ lost connection: Disconnected
[11:03:41] [Server thread/INFO]: Disconnecting client ___
[11:03:41] [Server thread/INFO]: ___ left the game[0m
```

**Comment by Athlaeos** [comment]
The error provided doesn't seem to be related to a failure to save player data, this is a crash report but I can't see where this crash is coming from. Where is the "error writing to DB" part?

**Comment by Zindswini** [comment]
Apologies, I must have incorrectly assumed the behavior. I just assumed that because it reset the row of whatever player had made progress and specifically skills that had made progress, it might have freaked out trying to write to the db.

**Comment by Athlaeos** [comment]
In 1.0.9 there was a bug fixed where, if the player left the server before their stats were loaded in, the database would save their stuff pre-loading and so essentially reset their progress. That could be the possible cause of this, so I guess you just need to update maybe? The crash and error seem unrelated to this issue, but I implemented something that should fix that error at least. It's unlikely it had anything to do with this reset though

**Comment by Zindswini** [comment]
Absolutely, I'll keep to the latest version and see if it happens again. Thank you!
